## Object Oriented Programming

In [1]:
class Lizard:
    def __init__(self, name):
        self.name = name
        
    def set_name(self, name):
        self.name = name

In [2]:
lizard = Lizard("deep")
print(lizard.name)

deep


In [3]:
lizard.set_name("lizard")
print(lizard.name)

lizard


## Neural Network example

In [4]:
import torch.nn as nn

ModuleNotFoundError: No module named 'torch'

In [ ]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.layer = None
        
    def forward(self, t):
        t = self.layer(t)
        return t

### CNN

In [ ]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
        
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)     # Linear = fully connected(fc) = dense
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
        
    def forward(self, t):
        t = self.layer(t)
        return t

SyntaxError: positional argument follows keyword argument (2073967581.py, line 5)

In [ ]:
net = Network()

In [ ]:
net

Network()

In [ ]:
print(net)

Network()


In [ ]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
        
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)     # Linear = fully connected(fc) = dense
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
        
    def forward(self, t):
        # implement the forward pass
        return t

In [ ]:
network = Network()

In [ ]:
print(network)

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)


In [ ]:
network.conv1

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))

In [ ]:
network.fc1

Linear(in_features=192, out_features=120, bias=True)

In [ ]:
network.out

Linear(in_features=60, out_features=10, bias=True)

In [ ]:
network.conv1.weight

Parameter containing:
tensor([[[[ 1.2429e-01,  5.0051e-03,  1.3083e-01,  1.9048e-01, -1.5119e-01],
          [ 4.5708e-02,  3.2135e-02,  7.6514e-02,  1.9863e-01, -2.7948e-02],
          [ 1.5544e-01, -2.2004e-02,  9.7023e-03, -1.0735e-01, -1.5901e-01],
          [-1.1732e-01,  1.3671e-01, -1.2025e-01,  1.3345e-02, -5.0585e-02],
          [-4.2812e-02, -7.0239e-02,  1.5959e-01,  1.6341e-01,  1.0769e-01]]],


        [[[-1.3043e-01, -1.5609e-01, -3.2823e-02,  6.2831e-02,  1.8395e-01],
          [-6.4102e-02,  1.6159e-01, -1.8309e-01,  7.3611e-02, -5.6824e-02],
          [ 1.0045e-02, -8.7375e-02, -1.3990e-01, -1.7672e-01,  1.9012e-02],
          [-1.9178e-01, -9.2164e-02, -1.2542e-01,  1.5310e-01, -3.6513e-02],
          [ 1.4820e-01,  8.6259e-02,  1.9526e-01, -8.9834e-02,  1.1156e-01]]],


        [[[-1.1659e-01,  1.5123e-01,  1.1730e-01, -1.4016e-01, -1.0931e-01],
          [-4.6759e-02,  1.6809e-01,  8.1342e-02,  6.3480e-02,  9.5646e-02],
          [ 5.0720e-02, -1.5473e-01,  5.9880e-

In [ ]:
network.out.weight

Parameter containing:
tensor([[-0.0858, -0.0465, -0.0183,  0.1056, -0.0943, -0.0145, -0.1029, -0.0064,
         -0.1059, -0.1043,  0.1032,  0.0273, -0.0690,  0.0692,  0.1017, -0.1235,
          0.0505, -0.0796, -0.1003, -0.0631, -0.0553,  0.0965,  0.1103,  0.0827,
         -0.0352, -0.0893,  0.1149, -0.0677,  0.1057,  0.0424,  0.1209, -0.1287,
         -0.0844,  0.0160,  0.0763,  0.0425,  0.0338,  0.0937, -0.0987, -0.0908,
          0.1039, -0.1061, -0.0786,  0.0341, -0.1195,  0.1169,  0.0707, -0.0736,
         -0.0796, -0.0266, -0.0039,  0.0217, -0.0650, -0.1118, -0.0383,  0.0751,
         -0.0956, -0.0127, -0.0315,  0.0158],
        [-0.0620,  0.0898,  0.0415, -0.1226, -0.0331, -0.1289,  0.0469, -0.0965,
         -0.0740,  0.0847, -0.0310,  0.0569, -0.1246, -0.0574, -0.0592, -0.0804,
          0.0797, -0.0997,  0.1167, -0.0740,  0.0395,  0.0555,  0.0071,  0.0054,
          0.1246,  0.1179,  0.0345, -0.0051,  0.0655, -0.0376,  0.0360, -0.0196,
         -0.1182,  0.1147, -0.0377,  0.10

In [ ]:
network.conv1.kernel_size

(5, 5)

In [ ]:
network.conv1.weight.shape

torch.Size([6, 1, 5, 5])

In [ ]:
network.conv2.weight.shape

torch.Size([12, 6, 5, 5])

In [ ]:
network.fc1.weight.shape

torch.Size([120, 192])

In [ ]:
network.fc2.weight.shape

torch.Size([60, 120])

In [ ]:
network.out.weight.shape

torch.Size([10, 60])

In [ ]:
import torch

In [ ]:
in_features = torch.tensor([1, 2, 3, 4], dtype=torch.float32)

In [ ]:
weight_matrix = torch.tensor([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6]]
,dtype=torch.float32)

In [ ]:
weight_matrix.matmul(in_features)      # 矩阵乘法

tensor([30., 40., 50.])

In [ ]:
for param in network.parameters():
    print(param.shape)

torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([12, 6, 5, 5])
torch.Size([12])
torch.Size([120, 192])
torch.Size([120])
torch.Size([60, 120])
torch.Size([60])
torch.Size([10, 60])
torch.Size([10])


In [ ]:
for name, param in network.named_parameters():
    print(name, '\t\t', param.shape)

conv1.weight 		 torch.Size([6, 1, 5, 5])
conv1.bias 		 torch.Size([6])
conv2.weight 		 torch.Size([12, 6, 5, 5])
conv2.bias 		 torch.Size([12])
fc1.weight 		 torch.Size([120, 192])
fc1.bias 		 torch.Size([120])
fc2.weight 		 torch.Size([60, 120])
fc2.bias 		 torch.Size([60])
out.weight 		 torch.Size([10, 60])
out.bias 		 torch.Size([10])
