In [1]:
import torch
import torch.nn as nn

In [5]:
weight_matrix.matmul(in_features)      # 矩阵乘法

tensor([30., 40., 50.])

In [3]:
in_features = torch.tensor([1, 2, 3, 4], dtype=torch.float32)

In [6]:
fc = nn.Linear(in_features=4, out_features=3)  # 4维转3维，weight为3x4

In [7]:
fc(in_features)              # callable function

tensor([ 0.3224,  1.0318, -0.2596], grad_fn=<AddBackward0>)

In [4]:
weight_matrix = torch.tensor([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6]]
,dtype=torch.float32)

In [8]:
fc.weight = nn.Parameter(weight_matrix)

In [9]:
fc(in_features)                        # 默认有bias

tensor([30.2941, 39.5454, 50.0272], grad_fn=<AddBackward0>)

In [10]:
weight_matrix.matmul(in_features)      # 矩阵乘法

tensor([30., 40., 50.])

In [14]:
fc = nn.Linear(in_features=4, out_features=3, bias=False)  # 关闭bias

In [16]:
fc.weight = nn.Parameter(weight_matrix)

In [17]:
fc(in_features)

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)