# Pytorch Tensor Explained

In [ ]:
import torch
print(torch.__version__)
torch.cuda.is_available()

In [6]:
import torch
t = torch.tensor([1, 2, 3])
t

tensor([1, 2, 3])

In [15]:
import torch
import numpy as np

## Tensor class


Tensors in PyTorch are represented using the `torch.Tensor` class

可以用Tensor类的构造函数创建一个Tensor


In [16]:
t = torch.Tensor()
type(t)

torch.Tensor

## Tensor attributes

In [9]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [10]:
device = torch.device("cuda: 0")
device

RuntimeError: Invalid device string: 'cuda: 0'

不同张量之间的操作必须需在同一个device上进行


layout表示张量在内存中是如何布局的，默认即可

In [11]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([1., 2., 3.])

In [12]:
t1.dtype

torch.int64

In [13]:
t2.dtype

torch.float32

In [14]:
t1 + t2

tensor([2., 4., 6.])

## Creation options using data

In [3]:
data = np.array([1, 2, 3])
type(data)

numpy.ndarray

In [4]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [5]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [6]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [7]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

#### special array

In [8]:
torch.eye(2)      # 单位矩阵

tensor([[1., 0.],
        [0., 1.]])

In [9]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [10]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [11]:
torch.rand(2, 2)

tensor([[0.3348, 0.7263],
        [0.1946, 0.6474]])

## Creating PyTorch Tensors - Best Options

In [1]:
import torch
import numpy as np

In [7]:
data = np.array([1, 2, 3])

In [8]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [9]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [10]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [11]:
torch.get_default_dtype()

torch.float32

In [12]:
torch.tensor(np.array([1, 2, 3]))

tensor([1, 2, 3], dtype=torch.int32)

In [13]:
torch.tensor(np.array([1., 2., 3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [14]:
torch.tensor(np.array([1, 2, 3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [2]:
data = np.array([1, 2, 3])

In [3]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [4]:
data[0] = 0
data[1] = 0
data[2] = 0

In [5]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [6]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


## Reshaping Explained

In [1]:
import torch
import numpy

In [2]:
t = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3]
],dtype=torch.float32)

In [3]:
t.size()

torch.Size([3, 4])

In [4]:
t.shape

torch.Size([3, 4])

In [5]:
len(t.shape)   # 秩

2

In [6]:
torch.tensor(t.shape).prod()     # 元素个数（将shape变成Tensor，接着用prod得到shape元素乘积，即原Tensor元素个数）

tensor(12)

In [8]:
t.numel()      # 元素个数的函数

12

In [9]:
t.prod()

tensor(1296.)

In [10]:
(2**4)*(3**4)

1296

In [11]:
t.reshape(1, 12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [12]:
t.reshape(2, 6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [13]:
t.reshape(3, 4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [14]:
t.reshape(2, 2, 3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [15]:
print(t.reshape(1, 12))
print(t.reshape(1, 12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [16]:
print(t.reshape(1, 12).squeeze())
print(t.reshape(1, 12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [17]:
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0))
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [18]:
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [19]:
t.reshape(2, 6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [20]:
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [22]:
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [23]:
print(t.reshape(3, 4).squeeze())
print(t.reshape(3, 4).squeeze().shape)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])
torch.Size([3, 4])


In [24]:
t.flatten()

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [25]:
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

In [26]:
flatten(t)             # reshape and squeeze

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [27]:
t.reshape(1, -1)       # reshape only

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [28]:
t.reshape(-1)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [29]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [30]:
torch.cat((t1, t2), dim=0)       # combine t1 and t2 row-wise (axis-0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [31]:
torch.cat((t1, t2), dim=1)       # combine t1 and t2 column-wise (axis-1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [32]:
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 2])

In [33]:
torch.cat((t1, t2), dim=1).shape

torch.Size([2, 4])

In [34]:
t = tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

NameError: name 'tensor' is not defined

In [35]:
t = torch.tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [36]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [37]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [40]:
t.shape[0]

3

In [41]:
t.reshape(t.shape[0], -1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

## Element-wise operations

In [1]:
import torch
import numpy as np

In [2]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [5]:
t1+t2

tensor([[10., 10.],
        [10., 10.]])

In [6]:
t1+2           # t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [7]:
t1-2           # t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [10]:
t1*2           # t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [11]:
t1/2           # t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [12]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [13]:
t1+2

tensor([[3., 4.],
        [5., 6.]])

In [15]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape)
    ,dtype=torch.float32
)

tensor([[3., 4.],
        [5., 6.]])

In [16]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype=torch.float32)

t2 = torch.tensor([2,4], dtype=torch.float32)

In [17]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

In [18]:
t1 + torch.tensor(np.broadcast_to(t2, t1.shape))

tensor([[3., 5.],
        [3., 5.]])

In [19]:
t2

tensor([2., 4.])

In [20]:
np.broadcast_to(t2, t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [21]:
t1+t2

tensor([[3., 5.],
        [3., 5.]])

## Argmax and Reduction ops

In [1]:
import torch
import numpy as np

In [2]:
t = torch.tensor([
    [0, 1, 0],
    [2, 0, 2],
    [0, 3, 3]
], dtype=torch.float32)

In [3]:
t.sum()          # 元素和

tensor(11.)

In [4]:
t.numel()        # 元素个数

9

In [5]:
t.sum().numel()

1

In [6]:
t.sum().numel() < t.numel()

True

In [7]:
t.sum()

tensor(11.)

In [8]:
t.prod()

tensor(0.)

In [9]:
t.mean()

tensor(1.2222)

In [10]:
t.std()

tensor(1.3017)

In [11]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [12]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [13]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [15]:
print(t[0])
print(t[1])
print(t[2])

tensor([1., 1., 1., 1.])
tensor([2., 2., 2., 2.])
tensor([3., 3., 3., 3.])


In [16]:
t[0]+t[1]+t[2]

tensor([6., 6., 6., 6.])

In [17]:
print(t[0].sum())
print(t[1].sum())
print(t[2].sum())

tensor(4.)
tensor(8.)
tensor(12.)


In [18]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [19]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [20]:
t.max()              # 最大值

tensor(5.)

In [21]:
t.argmax()           # 最大值下标

tensor(11)

In [22]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [24]:
t.flatten().argmax()

tensor(11)

In [25]:
t.max(dim=0)             # 每列的最大元素

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [26]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [27]:
t.max(dim=1)             # 每行的最大元素

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [28]:
t.argmax(dim=1)

tensor([3, 1, 3])

In [29]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [30]:
t.mean()

tensor(5.)

In [31]:
t.mean().item()

5.0

In [32]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [33]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)

In [1]:
print("let play")

let play


In [ ]:
foolish="你"
beauty=我
action=
identity=